project:
  type: website
  output-dir: docs
  

website:
  title: "ドワ*的世界"
  favicon: favicon.ico
  navbar:
    right:
      - about.qmd
      - icon: plurk
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css



