---
title: 歌曲總覽
execute:
  echo: false
  freeze: auto
jupyter: python3
tbl-colwidths: [5]
---

<style>
    .cell-output{width: 100vw;}
    .anchorjs-link {
        display :none;
    }
</style>
<link rel="stylesheet" href="../projects/twi_JP/style.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,500,1,200" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">



```{python}
#| column: screen-inset-shaded

%%capture --no-display
import sqlalchemy
import pandas as pd
import os
from IPython.display import display, Markdown
from dotenv import load_dotenv
import urllib
from urllib.parse import quote_plus
from tabulate import tabulate

load_dotenv()
db_password = os.getenv("DB_PASSWORD")
DATABASE_PASSWORD_UPDATED = urllib.parse.quote_plus(db_password)


### Create connection

engine = 'mysql://root:'+DATABASE_PASSWORD_UPDATED+'@localhost:3306/twiJP'
sqlalchemy.create_engine(engine)

### Connect
%reload_ext sql
%sql mysql://root:{DATABASE_PASSWORD_UPDATED}@localhost:3306/twiJP

### Query
result = %sql SELECT songName, releaseDate, Easy, Normal, Hard, Expert, Master, unit, TIME_FORMAT(songLength, '%i:%s') songLength, comboE, comboN, comboH, comboEX, comboMA, lyric, compose, arrange FROM song ORDER BY releaseDate

df = result.DataFrame()

    
tabulate(
      df, 
      headers=["名稱", "實裝日期", "Easy", "Normal", "Hard", "Expert", "Master", "團體", "時長", "Easy鍵數", "Normal鍵數", "Hard鍵數", "Expert鍵數", "Master鍵數", "作詞", "作曲", "編曲"], tablefmt="html", stralign="center", colalign="center", showindex=False
    )


```


<style>

  body {
        user-select: none;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
  }

  thead > tr > th {
    text-align: center !important;
  }
  tbody > tr > td {
    text-align: center !important;
  }

  th{
        background: hsl(154, 65%, 89%);
    }
    th:nth-child(1), th:nth-child(4), th:nth-child(5), th:nth-child(6), th:nth-child(7), th:nth-child(8), th:nth-child(11), th:nth-child(12), th:nth-child(13), th:nth-child(14), th:nth-child(15){
        width:3%;
    }
    th:nth-child(3){
        width:10%;
    }
    th:nth-child(2){
        width:20%;
    }
    th:nth-child(9){
        width:10%;
    }
    th:nth-child(10){
        width:5%;
    }

    tr:nth-of-type(2n){
        background: hsl(154, 55%, 95%);
    }

    @media (max-width: 650px){
        th {
            display:none;
        }

        td {
            display: grid;
            grid-template-columns:repeat(2, 1fr);
            justify-items: center;
        }

        td::before {
            font-weight : 900;
        }


        td:nth-child(1)::before {
            content:"ID";
        }
        td:nth-child(2)::before {
            content:"名稱";
        }
        td:nth-child(3)::before {
            content:"實裝日期";
        }
        td:nth-child(4)::before {
            content:"Easy";
        }
        td:nth-child(5)::before {
            content:"Normal";
        }
        td:nth-child(6)::before {
            content:"Hard";
        }
        td:nth-child(7)::before {
            content:"Expert";
        }
        td:nth-child(8)::before {
            content:"Master";
        }
        td:nth-child(9)::before {
            content:"團體";
        }
        td:nth-child(10)::before {
            content:"時長";
        }
        td:nth-child(11)::before {
            content:"Easy鍵數";
        }
        td:nth-child(12)::before {
            content:"Normal鍵數";
        }
        td:nth-child(13)::before {
            content:"Hard鍵數";
        }
        td:nth-child(14)::before {
            content:"Expert鍵數";
        }
        td:nth-child(15)::before {
            content:"Master鍵數";
        }
        td:nth-child(16)::before {
            content:"作詞";
        }
        td:nth-child(17)::before {
            content:"作曲";
        }
        td:nth-child(18)::before {
            content:"編曲";
        }

        td:first-child{
            padding-top:1rem;
        }
        td:last-child{
            padding-bottom:2rem;
        }
        img {
            margin: 0 !important;
        }
    }
    
</style>
<script>
  document.addEventListener('contextmenu', function (e) {
        e.preventDefault();
    });v
</script>
