---
layout: post
description: 原文章：https://corocoro.jp/special/305939/ | 此篇訪談翻譯僅作為個人練習。
categories: [一周年採訪, 翻譯, COROCORO]
title: COROCORO一周年採訪：DECO*27
date: "2022/04/11"
---

<br><br>
<span style="color:#4455dd">_——對許多粉絲來說DECO*27老師應該都很熟悉了……不過首先還是想先請您做個簡單的自我介紹……！！_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;好的！我是從2008年開始使用VOCALOID進行作曲、將樂曲上傳至影片共享網站，同時間對各式各樣的藝術家提供作曲。算一算也有……14個年頭了呢。

<br>

<span style="color:#4455dd">_——14年，真的是很長一段時間呢！！_
</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;是啊—。_COROCORO_(※訪談方網站) 是小學生非常喜愛造訪的網站，說不定我的活動年數比起那些孩子的歲數都還要大得多呢。

<br>

<span style="color:#4455dd">_——在P主（※指使用vocaloid創作並投稿歌曲的創作者）之中，DECO*27老師應該已經可稱為資深的創作者了吧？_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;我自己從來沒這麼想過，做的事情好像從20幾歲前半就一直沒變的感覺（笑）。不過仔細想想，真的是挺長的呢。

<br> 

<span style="color:#4455dd">_——您為『プロセカ』提供製作了『needLe__（ニードル）__』這首曲子。想聽一下您當初接到這份委託時的心境是如何！_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;那當然是，超級開心的啊！世界計畫，是一款虛擬歌手（Virtual Singer）和富有個性的角色們在同一個作品裡面相互融合的一款遊戲……所以覺得實在很有趣。所以當我收到委託時，記得也是抱著「好！來做吧！」熱情滿滿的氣魄開始的。那是感到開心的同時，想要作曲的慾望也跟著沸騰起來的瞬間呢。

<br> 

<span style="color:#4455dd">_——『needLe__（ニードル）__』是為Leo/need所寫的全新樂曲。Leo/need是一個成員全是女子的團體，請問您最初看到她們的印象是如何呢？_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;很單純覺得「也太可愛了吧！」。樂曲本身符合世界計畫的世界觀這點雖然很重要，但在這之前這首曲子是屬於她們的曲子呢。她們實際演奏的樣子、歌聲、情景等等意外的非常容易想像出來，在這層意義上她們給我的印象挺深刻的。

<br>  

<span style="color:#4455dd">_——在作曲的時候，印象很重要的樣子呢。_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;很重要呢—！我感受到的第一印象，和其他的LN粉絲、接下來接觸世界計畫看到LN的人們，應該相去不遠才對。如果抱持著和其他玩家較親近的印象、用我最一開始感覺到的想法放進曲子裡，我想應該會更流暢的傳達給粉絲們。所以說我很重視第一印象。

<br>  

<span style="color:#4455dd">_——將感受到的情緒，原封不動地直接寫進曲子裡這樣的意思嗎？_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;沒錯呢。將我收到的LN她們的故事，再添加上我的第一印象而寫出來的曲子……這樣的感覺。

<br>  

<span style="color:#4455dd">_——那麼，想請問一下『needLe__（ニードル）__』的主題是什麼！歌曲的方向性又是怎麼決定的呢？_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;主題是「羈絆」。LN的四人原本非常親密，後來發生了許多事情之後，關係變得有些緊張，我想好好表現出這樣的四人誕生出「即使如此還是一起組團吧！」的想法一路走來的經歷……。明明過去關係很親密結果逐漸分崩離析、彼此漸行漸遠，也有著悲傷的回憶。但最後，果然還是想要在一起繼續努力的心情，我想將這種「想法的力量」作為主題來寫曲子。

<br> 

<span style="color:#4455dd">_——有特別喜歡的歌詞嗎？_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;總共有兩個，第一個是副歌中間左右「將妳刺穿的這根針 我會為妳拔除的」的地方。曲名的「needle」同樣也是針的意思，是將主角們那份「讓妳感到痛苦難受的那根針，我會努力把它拔除解決掉的，所以請相信我吧」的心意包含在了裡面。「needLe」這個標題是將團名Leo/need調換順序重新組成的，但同時會選用「needle」這個詞也包含了一些想法在裡面。另外一個喜歡的地方就是，「哭了的時候就跟我說吧一定喔」這裡。好像有點難用語言去解釋，但「鼓勵的方式」不是有很多嗎？像是「不要哭了」，或是「哭了也沒關係的」等等。但是當我想到LN這個團體時，並不是這些措辭，而是想用更加……能讓人感受到彼此堅強的信賴的鼓勵方式來表現。所以在歌詞裡放入了，粗淺的關係下絕對不會說出口的「哭了的時候就跟我說吧一定喔」這樣的句子。這兩個就是我喜歡的地方……雖然是這麼說，但我其實還有很多喜歡的地方（笑）。

<br>  

<span style="color:#4455dd">_——是怎麼想出這麼有意義的語句呢！？_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;我平常都會盡量不使用太艱澀難懂的詞。全部都是有意識地使用日常對話中會出現的句子重新組織，再從裡面寫出合理的句子作為歌詞，同時也包含了全新的含義在裡面。這個是我平時在作曲時一直有在注意的一件事。

<br>  

<span style="color:#4455dd">_——那麼『needLe__（ニードル）__』又是花了多久進行製作的呢？_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;跟其他的曲子一樣，我其實並不是花很多時間在進行的製作的人呢。我想，從開始作曲開始……大概花了3天左右完成的吧。

<br>

<span style="color:#4455dd">_——3天！！？_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;從拿到主題後一直在腦中的思考時間當然也是滿久的（笑）。我會構思是這樣的風格嗎……作曲應該要這樣……等等，一定程度上在腦中確定好之後才進工作室開始製作的，所以如果加入那些思考時間的話時間還會在更長一點。不過其實也並不會思考太多。尤其製作『needLe（ニ―ドル）』的時候，主題定的很明確，角色也非常地有魅力，記憶中寫得非常順利。

<br>  

<span style="color:#4455dd">_——世界計畫真的是不僅世界觀作的很好、角色形象也非常鮮明，從這個層面來看很容易去做形象化呢。_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;沒錯！就是那樣！

<br>  

<span style="color:#4455dd">_——那麼，『needLe（ニードル）』當初在遊戲實裝之後的感想是？_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;首先純粹感到非常感動。因為是注入了很多心思的曲子，看到在遊戲裡實裝、LN她們在演奏的樣子，打從心底覺得｢真是太好了！｣。跟自己原本想的樣子跟畫面非常契合，更加確信這樣可以比想像中更有力地向玩家傳達我的想法。當想到這件事的時候，感到非常的興奮呢。

<br>  

<span style="color:#4455dd">_——也有看過粉絲們的反應了嗎。_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;自從世界計畫發布、了解遊戲的世界觀後再到我的頻道聽『needLe（ニードル）』的完整版的人還不少呢。從那些人收到很多類似「跟LN的風格非常搭，超級喜歡的！｣的反應。這真是、太令人高興了……！果然為了LN而寫的曲子，能得到她們粉絲的認可，身為創作者就覺得很值得了。

<br>

<span style="color:#4455dd">_——好的那麼從這裡，想跟DECO*27老師進行「有關於V家P主的全面疑問｣的QA環節。我想COROCORO的讀者裡應該也有很多將來想要成為P主的少年少女們，我想請您回答可能會幫助到他們的問題。首先......想知道您成為P主的契機！_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;2007年我開始在影片分享平台投稿的時候，初音未來才剛出現沒多久，但當時在完全不知道的情況下聽到kz先生的曲子 『Packaged』，獲得了很大的衝擊。不過，我那時對 「Vocaloid｣ 一點概念也沒有，因此只覺得活生生有很可愛的初音未來是真實存在、聲線有些獨特的孩子呢（笑）。直到去查了一下，原來初音未來是聲音合成軟體、有Vocaloid的存在......得知這些後我又受到了一次衝擊。於是我開始產生了想試試看的想法，開始將自己作的曲子使用Vocaloid進行投稿。

<br>

<span style="color:#4455dd">——嗯嗯！</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;我覺得「想成為P主！」有這樣想法的孩子，應該是看到現在作為P主而活躍的藝術家所以產生了「我也想成為那樣的人！」的想法。這跟我是一模一樣的。前面也提到kz先生，我也是當時聽著各個音樂家所製作的Vocaloid曲子而產生了憧憬，然後才想成為P主。

<br>

<span style="color:#4455dd">_——產生憧憬是一切的開始吧。_</span>

是的。就是覺得……看到了非常帥氣又耀眼的事物呢，對當時的我來說。

<br>  

<span style="color:#4455dd">_——走到現在，一路上有遇到過特別辛苦的事情嗎？_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;如果是指技巧方面的話，該如何讓初音未來唱得更好之類的全是靠著自己摸索的……啊不過，與其說辛苦其實更多的是快樂呢……。因為是我最早開始創作的作品，所以受到的批評也不少也說不定（笑）。當時也有用有色眼鏡看網路作品的風潮，這部分也是比較辛苦的地方。不過現在那種風氣已經幾乎不見了呢。反而作為P主成為了一種品牌一樣。不過當時受到的批評也多，因此也養成了一種「總有一天一定要讓你們覺得『這好好聽啊！』！」叛逆心態。

<br>  

<span style="color:#4455dd">_——那麼，為了成為P主，有什麼必須要有的技能嗎？_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;我認為樂器還是要學一項會比較好。如果可以的話，吉他或是鋼琴二者擇一。P主雖然是自己創作，不過在作曲的時候有碰過樂器我覺得會比較容易有想法。不過P主中也有很多人並不會彈樂器就是了。然後就是聽聽自己喜歡的曲子，花點時間深入研究一下會比較好。在聽喜歡的音樂時，跟實際上在作曲的時候，腦袋的運作方式會不太一樣。自從我真的開始作曲後再去聽過自己曾經喜歡的曲子，就常有「原來如此！原來這邊是這樣啊！」的感想，像打開新世界的大門一樣。再來……不管如何，「我很喜歡VOCALOID！」的心情是最重要的！這種情感聽者是絕對感覺得出來的，所以保持著喜愛的心情是很重要的。

<br>  

<span style="color:#4455dd">_——以「喜歡」的心情作為基礎做出來的東西會很不一樣呢。_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;沒錯，完全不一樣！我覺得吸收知識的道路會因此變得非常寬闊，所以希望大家能好好珍惜「喜歡」這個心情。

<br>

<span style="color:#4455dd">_——那麼，有沒有甚麼事情讓你深感「成為P主真是太好了！」？_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;應該是透過我的曲子知道VOCALOID後也開始製作很多的樂曲這件事吧。我也是在2007年知道這個世界後受到不小的衝擊、想著「總有一天，我也想靠自己的努力，把這份感動傳達給其他人！」在漫長的活動期間，從不同世代的人們獲得「很棒的曲子呢！」、「我愛上初音未來了！」等等的回應，是我覺得成為P主後最棒的事情。

<br>  

<span style="color:#4455dd">_——看著現在憧憬成為P主的孩子不斷增加，我認為這真的是非常有意義的一件事。_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;從要共事的工作夥伴聽到「我從10年前還是國中生的時候就在聽您的曲子了了！」的情況也增加了。10年前，那時候的我光是作出曲子就已經拼盡全力了，「聽著這首曲子的孩子們未來會是如何呢……」什麼的根本沒想過這種事。但是聽那時候的曲子的人們現在都已經長大了，有些成為P主、有些成為歌手……。「您作的曲子是我從事這份工作的契機！」，這樣的對話也變多了，覺得……嗯，我真的感到很光榮。

<br> 

<span style="color:#4455dd">_——現在閱讀這篇訪談而點燃熱情的孩子們，未來搞不好會在DECO老師的面前出現喔。_</span>  

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;啊哈哈哈，對欸！會變對手囉！好期待喔！

<br> 

<span style="color:#4455dd">_——擁有相同目標的人增加會很開心吧。_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;很開心啊—！現在也有很多年輕的P主們不斷創作出很棒的歌曲，很多粉絲也做出很好的評價。我一邊想著「好棒啊」，一邊也有些悔恨地想著「可惡！」。我也不打算安於現狀，未來還要繼續努力才行。

<br>  

<span style="color:#4455dd">_——那麼……面對以成為P主為目標的青少年們，想請您作為前輩為他們加油打氣！_</span>

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;我自己是抱著「這裡是我最能享受到快樂的地方呢」一路走來的。現在想著「我愛VOCALOID！」或是「我想成為P主！」的孩子們，也是感覺這個業界正在成長為一個可以開心進行活動的環境。未來如果真的成為了P主……我非常期待能在同一個領域、同一個稱呼底下一起炒熱業界的風氣，所以如果有抱持這個夢想的人，請務必繼續加油！

<br> 

<span style="color:#4455dd">_——最後，世界計畫也迎來了一周年了！希望老師能給予一些祝福的話……！_</span>  

<code><span style="color:#4455dd">DECO*27</span></code>&nbsp;&nbsp;已經一周年了呢！時間過得真快呢～。雖然過了一年，每當追加新曲時還是會上推特的趨勢，我總是覺得果然是人氣非常有實力的啊。關於曲子的部分，看到熟悉VOCALOID早期的粉絲，還有年輕的粉絲在網路上進行討論和考察，就覺得世界計畫是一個將新舊VOCALOID粉絲連接起來的場所，非常感動呢。作品迎來一周年真的非常了不起，未來也希望可以朝向二、三周年繼續向上邁進！

<br>  

<span style="color:#4455dd">_——非常感謝您參與今天的訪談！！_ </span>

___—————————————(完)————————————___

※原文共5906字