---
toc: false
layout: post
description: 原文章：https://media.colorfulpalette.co.jp/n/n120951ae0e98 | 此篇訪談翻譯僅作為個人練習。
categories: [官方部落格採訪, 譜面製作, 翻譯, ColofulPalette] 
title: 譜面製作採訪
format: html
date: "2022/08/11"
---

<br><br><br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;由Colorful Palette與SEGA合作推出的「プロジェクトセカイ カラフルステージ！ feat. 初音ミク」中的隨著追加實裝樂曲數增加，在2022年6月達到了200首曲目。 因此，這次我們採訪了製作節奏遊戲譜面的「製譜團隊」，講述了製作過程以及譜面上的一些巧思。

  
<br><br><br>
  

### 制作流程介紹

<br>
<blockquote style="font-weight:bold;"> ——請告訴我們製譜團隊的工作。 </blockquote>
<br>
  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;我們是負責世界計畫遊戲譜面製作的團隊。 通過聆聽音樂，將構成音樂的各種元素，如聲音、樂器、節奏、歌詞以及創作者的感受，利用音鍵的類型、形狀和排列表達出來，創造出玩家覺得有趣的譜面，這就是我們的工作。

  
  
<br>
<blockquote style="font-weight:bold;"> ——請介紹一下製作譜面的流程。</blockquote>
<br>
  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;儘管這是一個粗略的流程，但我們是以下述過程為準進行製作的。


&emsp;&emsp; 1.  確定每首歌曲的製作負責人  <br>  
&emsp;&emsp;&emsp; 2.  聆聽音樂，創建譜面的基底   <br>  
&emsp;&emsp;&emsp; 3.  修飾譜面  <br>  
&emsp;&emsp;&emsp; 4.  進行最終品質檢查 <br>  

  
  
<br>
<blockquote style="font-weight:bold;"> ——在製作譜面時，您會注重哪些事情？</blockquote>
<br>
  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 世界計畫是使用長期以來深受 VOCALOID 粉絲喜愛的著名歌曲，以及創作者為世界計畫而編寫的歌曲。 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;我們謹記被委託製作的是粉絲們非常珍視的歌曲的譜面，因此想創作「最大限度地展現歌曲的魅力並給VOCALOID和世界計畫的粉絲都能深受感動的譜面」。 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;我們不僅僅是為了創作與音樂相匹配的譜面，更是為了創作出能讓玩家在節奏遊戲中享受「好玩」、「有趣」“體驗”，成員之間毫無保留地交流彼此的意見並進行製作。 

<br><br><br>

### 實裝譜面精選

<br>
<blockquote style="font-weight:bold;">——在世界計畫中實裝的歌曲數量已超過200首了，想請您們稍微介紹一下部分譜面其中的巧思有哪些。 </blockquote>
<br>
  

_**「マトリョシカ」**_　

作詞：ハチ　作曲：ハチ　編曲：ハチ

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 我們在マトリョシカ歌詞中出現的「數字」的表達方式做了一些功夫。迄今為止，即使在製作中也有以音鍵形式表達數字的譜面，但為了再現這首歌的MV中出現的「特色字型」，數字部分的音鍵我們嘗試了大約20種排列方式。除了數字之外，也有融合了很多歌詞中令人印象深刻的詞進去，歡迎大家找這些亮點。


<br><br>
  

_**「STAGE OF SEKAI」**_

作詞：針原翼（はりーP）　作曲：針原翼（はりーP）　編曲：棚橋 EDDY テルアキ

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  因為它是一首樂團的歌曲，所以有意識地配合樂器聲音製作譜面，讓玩家舒適地敲擊音鍵。我們沒有放什麼機關，而是強調點擊時「SE（註：Sound Effect，點擊音效）和音鍵出現的時間點聽起來很舒服」。我們希望玩家透過點擊的音效配合樂器演奏的聲音，感覺自己正在和LN一起演奏一樣而製作這樣的譜面。


<br><br>


_**「モア！ジャンプ！モア！」**_

作詞：ナユタン星人　作曲：ナユタン星人　編曲：ナユタン星人

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; モア！ジャンプ！モア！是第一首MMJ活動實裝的曲子，MMJ在那個時候的很多歌曲都有「慢節奏」和「輕柔曲調」的元素，因此製作的譜面難易度相對簡單。對於這首歌，我們希望玩家能從「快節奏」、「振奮人心的曲調」元素中感受到成就感，因此第一次設置了高難度。這是一首明亮又充滿偶像風格的歌曲，所以也將御宅藝節奏反映在譜面中。希望在享受節奏遊戲的同時，也能感覺到自己在應援MMJ一樣。 

  
<br><br>
  

_**「Awake Now」**_

作詞：牛肉　作曲：雄之助　編曲：雄之助

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; VBS有很多快節奏的歌曲。大部分都是重視在玩的同時，也可以享受樂曲帶來的節奏感，這首曲子也是為了能讓玩家感受到樂曲的節奏而配置的譜面。 MASTER譜面採用需要左右手指位置互換的配置。這種編排以往都是在Lv.32及以上的譜面才會見到，但由於這首樂曲的節奏較慢，就算是不擅長高難度譜面的人說不定也可以更容易去挑戰。希望玩家能享受這首歌特色之一的“跳躍節奏”（註：用以形容聽起來是蹦蹦跳一樣的節奏音樂）。

  
<br><br>
  

_**「にっこり^^調査隊のテーマ」**_

作詞：じーざす　作曲：じーざす　編曲：ワンダフル☆オポチュニティ！

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 這是一首充滿WS風格、元氣滿滿的歌曲，所以我想在譜面上表達它的活潑趣味。在譜面中放入了許多以音鍵表現3DMV和歌詞中出現的小道具和符號的小機關。此外，3DMV的“人物動作”充分利用音鍵和SE表現在譜面上，譜面與3DMV重疊時產生的協同效應旨在讓節奏遊戲的譜面玩起來更加有趣。即使是那些不擅長高難度譜面的人也很享受用自動播放看音樂影片和譜面的話，我們也覺得非常高興。


<br><br>  


_**「バグ」**_

作詞：かいりきベア　作曲：かいりきベア　編曲： —

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 這首譜面旨在表達歌詞中描繪的「bug」感和歌曲本身讓人中毒般的快節奏旋律。在MASTER譜面的後半部分，排列著乍一看像「bug」的音鍵，以及重複相同動作的音鍵。在遊玩時可能會逐漸感到手指和大腦麻痺也說不定。希望大家也體驗到自己好像也要發生錯誤一樣的奇妙感覺。 

<br><br><br>

###  對未來製作的展望
<br>
<blockquote style="font-weight:bold;"> ——自發布以來有什麼是沒有改變的事物、又有什麼發生了改變呢？ </blockquote>
<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 通過節奏遊戲創造「好玩」、「有趣」“體驗”的願望沒有改變。 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 改變的是，做出更加活用各個團體特色、更加擁有世界計畫風格的譜面這件事。隨著遊戲內故事劇情的推進、角色的成長和關係的發展，團體的特色也不斷加深。我認為譜面有必要考慮到這些角色的成長並且一起不斷進化。

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  另外，隨著遊戲中實現的歌曲數量越來越多，為了不讓體驗僵化，接下來還想要挑戰更多嶄新的嘗試。 

<br>
<blockquote style="font-weight:bold;"> ——請告訴我們您對未來的展望。 </blockquote>
<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 接下來也要繼續創作讓玩家覺得作為節奏遊戲很有趣的譜面。

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 平常就在玩節奏遊戲的人也不少，所以我們想進一步磨練我們的技能，以提供具有挑戰性的譜面。

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 同時也希望不擅長節奏遊戲的玩家也可以享受遊玩體驗，所以想創作出可以讓他們享受到自身進步的譜面。我希望可以做出從NORMAL到HARD、從HARD到EXPERT，這樣不斷向上邁進的橋樑般的譜面。

  
<br><br><br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 世界計畫即將迎來兩週年，非常感謝所有支持我們的粉絲。

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 未來會加入很多好聽的歌曲，所以我想為了能總是傳遞新的快樂和樂趣，在每一張譜面上都盡全力製作。

  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 感謝您一直以來對世界計畫節奏遊戲的支持。