---
layout: post
description: 原文章：https://corocoro.jp/special/307943/ | 此篇訪談翻譯僅作為個人練習。
categories: [一周年採訪, 翻譯, COROCORO]
title: COROCORO一周年採訪：Mitchie M
date: "2022/04/25"
---

<br><br><br>
{% include info.html text="※此篇是以郵件通信的訪談所構成。" %}
<br>
<span style="color:#88dd44">_——首先想先請您做個簡單的自我介紹……！！_</span>

<code><span style="color:#88dd44">Mitchie M</span></code>&nbsp;&nbsp;初次見面大家好，我是Mitchie。身為調聲（※對VOCALOID聲音進行參數上的調整）評價很好的P主，今年活動時間滿10周年了。在世界計畫中，製作的樂曲除了主題曲之一的「ワーワーワールド」（和Giga老師共同製作），還有MORE MORE JUMP！所演唱的「アイドル新鋭隊」、「ビバハピ」也都有收錄進遊戲中。

<br>

<span style="color:#88dd44">_——您為世界計畫提供製作了樂曲，想知道您當初接到這份委託時的心境是如何！_</span>

<code><span style="color:#88dd44">Mitchie M</span></code>&nbsp;&nbsp;收到委託的時候是在發售前，能接到最一開始的原創團體曲的委託，真的感到非常榮幸。但是同時，也有點「必須要做出讓遊戲打出人氣的曲子不可」……這樣的壓力存在。不過，收到「既可愛又新鮮、抱有希望P主的秘密！偶像曲子」這樣的要求，是已經有個固定的形象，再加上這也是我自己滿拿手的類型，所以最後也是抱著「盡全力去做吧！」的心情的。

<br>

<span style="color:#88dd44">_——關於您所負責的團體．角色主題曲，第一印象是什麼呢？_</span>

<code><span style="color:#88dd44">Mitchie M</span></code>&nbsp;&nbsp;總之就是很可愛、「這就是偶像！」的感覺呢。看起來是跟身為虛擬歌手的初音未來親和性最好的團體。在我讀過故事後，知道團體內的成員都非常的有個性，而且從各自抱著煩惱到最後在MORE MORE JUMP！重新賭上自己的熱情的想法也深深感動到了我。

<br> 

<span style="color:#88dd44">_——想知道在製作「アイドル新鋭隊」時訂的主題是什麼！歌曲的方向性又是怎麼決定的呢？_</span>

<code><span style="color:#88dd44">Mitchie M</span></code>&nbsp;&nbsp;主題就如曲名所標示的一樣就是「親衛隊」（※由同一偶像的支持者們所組成的高度組織紛絲團。新鋭隊和親衛隊發音一樣）。其實我以前在心底一直有「放入像80年代親衛隊那樣的打call的偶像曲子」這個想法。然後這次接到MORE MORE JUMP！的時候，就覺得很適合她們，剛好利用這次機會將這個想法實現出來。只不過，是有擔心過現在的年輕人會不會不懂這個梗（笑）。

<br>

<span style="color:#88dd44">_——有特別喜歡的歌詞嗎？_</span>

<code><span style="color:#88dd44">Mitchie M</span></code>&nbsp;&nbsp;副歌最後的「因永不幻滅的夢而凝聚  We are 偶像新銳隊 MORE MORE JUMP！！」（消せぬ夢で結ばれた We are アイドル新鋭隊 MORE MORE JUMP！！）這句話特別喜歡。選用「新銳隊」而不是親衛隊的原因，就是有包含「走在潮流尖端的新生代偶像」這個意思，也是MORE MORE JUMP！唱出她們自己的故事。當然同時也有包含代表粉絲的「親衛隊」的意思。這段飽含著成員各自對著有不想放棄的夢想的堅持，所以在曲子裡面是最重要的一段歌詞呢。

<br>

<span style="color:#88dd44">_——這個問題可能跟上述的問題相似有點不好意思，不過想請教您有沒有認為「這裡必聽」的地方呢！能跟我們分享像是特別點、或是有特別在乎的一些細節也非常感謝！_ </span>

<code><span style="color:#88dd44">Mitchie M</span></code>&nbsp;&nbsp;親衛隊的口號有特別花心思製作的。其實世界版本和虛擬歌手版本的口號稍微不同，口號中的名字會依照唱的人而更改是比較特別的一點。錄音的時候果然還是難以像真正的親衛隊那樣大人數呼喊口號，最後是用少數人的聲音加上效果模擬出很多人在呼喊的感覺。裡面有放了KAITO的聲音，還錄了我自己打call的聲音（笑）。

<br> 

<span style="color:#88dd44">_——製作日期大約是多久呢？相較之下算是難產，還是一路順暢……等等，想請您分享製作的難度大概在哪裡呢……！_</span>

<code><span style="color:#88dd44">Mitchie M</span></code>&nbsp;&nbsp;就像前面提到的，曲子的點子是之前就溫存起來的，所以沒有發生進度陷入停滯的情況，相較起來是一路很順利的製作完成。不過因為我同時製作世界版本和虛擬歌手版本，再加上兩個版本的口號稍微不同，所以作業量龐大，到最後還是花了大概二到三個月左右。特別是虛擬歌手版本裡每個人都需要調聲，所以相當辛苦呢。然後我自己也有參與世界版本的混音，要將人聲和初音未來的聲音在質感上完美地契合也很困難。但是，像這樣把初音未來的聲音和人聲並列在一起進行混音的情況其實很少遇到，在調聲未來這方面學到了很多。

<br> 

<span style="color:#88dd44">_——準備實裝上遊戲的樂曲，第一次看到的時候的感想是？_</span>

<code><span style="color:#88dd44">Mitchie M</span></code>&nbsp;&nbsp;對3DMV的品質很驚訝呢。果然樂曲配上影片後，角色的聲音聽起來比以往都還要更有活力，當下非常感動。還有舞蹈本身很可愛呢。遊戲上線後，很多玩家換上男性角色讓他們跳這個MV、玩得不亦樂乎的，這個倒是沒有預想到（笑）。

<br> 

<span style="color:#88dd44">_——在遊戲實裝後，有獲得什麼樣的反響呢？_ </span>

<code><span style="color:#88dd44">Mitchie M</span></code>&nbsp;&nbsp;我有去看了推特的反應，10幾歲的孩子們都有在聽，和往常V家樂曲的聽眾不太一樣的人們，我的曲子也到了他們面前這些事讓我很很開心呢。「吃飯時間的播送有聽到アイドル新鋭隊！」這類的推特看到不少次，覺得世界計畫的影響力好厲害呀。我身邊也有親戚家的孩子很哈世界計畫，還跟我要了簽名（笑）。

<br> 

<span style="color:#88dd44">_——喜歡這首曲子的粉絲非常地多，想請你跟這些粉絲說幾句話！_</span>

<code><span style="color:#88dd44">Mitchie M</span></code>&nbsp;&nbsp;「アイドル新鋭隊」是一首不管何時聽都會打起精神的曲子，所以如果在日常生活中聽著聽著、變得更加正向的話我會感到非常開心。若是之後有在LIVE中出現的話，請盡情地大聲跟著打call炒熱氣氛吧。

<br> 

<span style="color:#88dd44">_——好的那麼從這裡，想跟Mitchie M老師進行「有關於V家P主的全面疑問｣的QA環節。我想COROCORO的讀者裡應該也有很多將來想要從事V家P主的少年少女們，我想請您回答可能會幫助到他們的問題。首先......您成為P主的契機是！？_</span>

<code><span style="color:#88dd44">Mitchie M</span></code>&nbsp;&nbsp;2011年投稿第二首Vocaloid曲子「FREELY TOMORROW」的時候收到「初音未來像人類一樣在唱歌喔！」這樣的評價，產生很大的迴響這件事就是契機。其實在那個時候我還不太熟悉Vocaloid的世界。但是多虧那首曲子變得熱門，讓我了解到Vocaloid世界的魅力和有趣之處，一直到現在都還是作為P主在進行活動。

<br> 

<span style="color:#88dd44">_——為了成為P主，會需要什麼樣的技能呢？比如說能讀懂樂譜是必要的！學一項樂器會比較好！等等，想請您分享有什麼可以給孩子們當一個參考的建議呢！_</span>

<code><span style="color:#88dd44">Mitchie M</span></code>&nbsp;&nbsp;會彈樂器或是會讀樂譜這些當然是有幫助的。但是比起這些更重要的是能創作出有衝擊性曲子的「發想力」吧。現在多虧了科技的進步，誰都有可能做得出高品質的樂曲。所以接下來對於可以創作出有想法的曲子的人來說，原創性、還有容易被大眾注意到是很重要的。為了達成這個目標，多聽自己喜歡的音樂類型以外的曲子、打開自己的視野是很重要的。

<br> 

<span style="color:#88dd44">_——有沒有什麼讓你深感「成為P主真是太好了！」的事情呢？_</span>

<code><span style="color:#88dd44">Mitchie M</span></code>&nbsp;&nbsp;這種事可多了！尤其我的第一張專輯是請擔任新世紀福音戰士人物設計的貞本義行老師繪製、第二張專輯是請擔任超時空要塞系列人物設計的美樹本晴宴老師繪製的，非常開心呢。我從孩童時代就很喜歡兩位的繪畫，沒想到能請到兩位幫忙繪製專輯封面真的很感動。還有，在初音未來交響樂曾經擔任主題曲的製作及編曲也是相當貴重的經驗。大型交響樂團演奏自己的編曲實在是一個很稀有的事情。第一次聽到許多專業的演奏家在演奏自己譜寫的曲子、充滿壓倒性魄力的交響樂時，真的相當感動。

<br> 

<span style="color:#88dd44">_——面對以成為P主為目標的青少年們，想請您作為前輩為他們加油打氣！_</span>

<code><span style="color:#88dd44">Mitchie M</span></code>&nbsp;&nbsp;坦白說能成為P主過生活的人只有那麼一小部分的人，是相當狹窄的道路。但是，能找到一個目標前進並熱衷於自己喜愛的事情上，我認為對未來的人生會產生很大的幫助。如果想以成為P主為目標，希望就盡全力去做，創造出有品質、前所未聞的有趣音樂吧。

<br> 

<span style="color:#88dd44">_——最後，世界計畫也迎來了一周年了！希望老師能給予一些祝福的話……！_ </span>

<code><span style="color:#88dd44">Mitchie M</span></code>&nbsp;&nbsp;恭喜世界計畫來到了一週年！現在回過來看，世界計畫成為超人氣遊戲，而且還有幸擔任主題曲和團體主題曲的製作我感到相當光榮。對世界計畫來說這還只是開始而已，未來除了期待嶄新的發展外，也希望它能成為一款被粉絲長久愛戴的遊戲。

<br> 

<span style="color:#88dd44">_——非常感謝您參與今天的訪談！！_</span>

___——————————（完）——————————___

※原文共3810字